<?php
/**
 * - The main loop is based on: \BASE\DEFAULT\template\catalog\product\list.phtml
 * - Replaced: $_helper->productAttribute($_product, $_product->getName(), 'name')
 *   with: $this->htmlEscape($_product->getName())
 * - Added class "first" to grid
 */
?>
<?php
    $_productCollection = $this->getLoadedProductCollection();
    $_helper = $this->helper('catalog/output');
	$themeHelper = $this->helper('themeadmin');
	//$_productCollection->setPageSize(4);
?>
<?php if ($_productCollection && $_productCollection->getSize()): ?>
	
<?php
    $_collectionSize = $_productCollection->count();
    $_columnCount = $this->getColumnCount();
    $imgWidth = 190;
    $imgHeight = 190;
    switch($_columnCount) {
    case 4:
        $imgWidth = 190;
        $imgHeight = 190;
        break;
    case 5:
        $imgWidth = 154;
        $imgHeight = 154;
        break;
    }
    //Check aspect ratio settings
    $keepAspect = $themeHelper->getCfg('category/aspect_ratio');
    if ($keepAspect)
        $imgHeight = 0; //Height will be computed automatically (based on width) to keep the aspect ratio
    
    //List item height callculation
    $gridMinHeight = intval($themeHelper->getCfg('category_grid/grid_item_min_height'));
    
    //Count panes
    $_paneCount = ceil($_collectionSize / $_columnCount); //Current number of rows (which means: number of tabs and panes)
    
    //Create random value. It will help to identify each instance of the slider.
    list($usec, $sec) = explode(' ', microtime());
    $randomSeed = (float) $sec + ((float) $usec * 100000);
    mt_srand($randomSeed);
    $r = mt_rand();
?>
    
<div class="itemslider-wrapper">

    <?php if($_paneCount > 1): ?>
        <a id="itemslider-back-<?php echo $r; ?>" class="backward browse-button" href="#">previous</a>
        <a id="itemslider-for-<?php echo $r; ?>" class="forward browse-button" href="#">next</a>
    <?php endif; ?>
    
    <div id="itemslider-<?php echo $r; ?>" class="itemslider" style="top: 20px;">
		<?php $i=0; foreach ($_productCollection as $_product): ?>
        
        	<?php if ($i++%$_columnCount==0): ?>
            	<div class="slide">
            	<ul class="products-grid spec-grid spec-grid<?php echo $_columnCount;?>col grid-wide grid-actions-absolute grid-standalone clearer">
            <?php endif; ?>
            
                <li class="item<?php if(($i-1)%$_columnCount==0): ?> first<?php elseif($i%$_columnCount==0): ?> last<?php endif; ?>" <?php if($gridMinHeight) echo 'style="min-height:'.$gridMinHeight.'px;"'; ?>>
                    <a href="<?php echo $_product->getProductUrl() ?>" class="product-image">
                    
                    	<img src="<?php echo $themeHelper->getImgUrl($this, $_product, $imgWidth, $imgHeight, 'small_image'); ?>" width="<?php echo $imgWidth;?>" alt="<?php echo $this->htmlEscape($_product->getName()) ?>" />
                    
                    	<?php // Code displaying product labels "new" and "sale". It's a copy of 'catalog/product/view/media_labels.phtml'
						require('view/media_labels.inc.phtml'); ?>
                    
                    </a>
                    <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php //my:del echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?>
                        <?php echo $this->htmlEscape($_product->getName()) ?>
                        </a></h2>
                    <?php if($_product->getRatingSummary()): ?>
                    <?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
                    <?php endif; ?>
                    <?php echo $this->getPriceHtml($_product, true) ?>
                    <div class="actions">
                        <?php if($_product->isSaleable()): ?>
                            <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
                        <?php else: ?>
                            <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                        <?php endif; ?>
                        <ul class="add-to-links">
                            <?php if ($this->helper('wishlist')->isAllow()) : ?>
                                <li><a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="link-wishlist" title="<?php echo $this->__('Add to Wishlist'); ?>"><?php echo $this->__('Add to Wishlist') ?></a></li>
                            <?php endif; ?>
                            <?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
                                <li><span class="separator">|</span> <a href="<?php echo $_compareUrl ?>" class="link-compare" title="<?php echo $this->__('Add to Compare'); ?>"><?php echo $this->__('Add to Compare') ?></a></li>
                            <?php endif; ?>
                        </ul>
                    </div>
                </li>
            
            <?php if ($i%$_columnCount==0 || $i==$_collectionSize): ?>
            	</ul>
                </div>
            <?php endif; ?>
            
		<?php endforeach ?>
    </div> <!-- end: itemslider -->
</div> <!-- end: itemslider-wrapper -->
<script type="text/javascript">
//<![CDATA[
  jQuery(function() {
	jQuery("#itemslider-<?php echo $r; ?>").cycle({
      fx: 'scrollHorz',
	  easing: 'easeInOutCubic',
	  timeout: <?php echo intval($themeHelper->getCfg('product_slider/timeout')); ?>,
	  speed: <?php echo intval($themeHelper->getCfg('product_slider/speed')); ?>,
	  sync: 1,
	  pause: 1,
	  prev: "#itemslider-back-<?php echo $r; ?>",
	  next: "#itemslider-for-<?php echo $r; ?>",
	  manualTrump: 0,
	  cleartypeNoBg: true
	});
  });
//]]>
</script>
<?php endif; ?>