<fieldset class="form-list">
<?php if($this->getMethod()->get_icon()):?>
<img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'catalog/product/placeholder/'.$this->getMethod()->get_icon() ?>" width="269px" height="50px" cursor: pointer;
onClick='window.open( "http://202.9.84.88/documents/payment/4vn.html","myWindow","status = 0,toolbar=0,location=0,menubar=0,directories=0,scrollbars=1,height = 600, width = 730, resizable = 0")'/>
<?php endif;?>		
</fieldset>
